linters-settings:
  staticcheck:
    checks:
      - all
      - "-QF1012"  # disable "use fmt.Fprintf instead of WriteString(fmt.Sprintf)"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gofmt
